# Generated by Django 4.0.2 on 2022-02-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_alter_plantedtree_planted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='planted_at',
            field=models.DateTimeField(),
        ),
    ]
