# Generated by Django 4.0.2 on 2022-02-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_alter_plantedtree_planted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantedtree',
            name='planted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
